bootstrap.servers=localhost:9092,localhost:9093

group.id=sasl-consumer-2

security.protocol=SASL_SSL
ssl.protocol=TLSv1.2
ssl.truststore.location=../k/ssl/kafka.consumer.truststore.jks
ssl.truststore.password=123456
#ssl.keystore.location=../k/ssl/kafka.consumer.keystore.jks
#ssl.keystore.password=123456
#ssl.key.password=123456

sasl.mechanism=SCRAM-SHA-512
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="sasl-consumer-2" password="Bro123";
